from typing import List, Literal
from pydantic import Field
from final_code.states.AgentInstructions import AgentInstructions
from final_code.states.ReqAnalysis import ReqAnalysis
from final_code.states.DryRunState import UseCaseAnalysis
from typing import List
from final_code.states.BaseCopilotRenderingState import BaseCopilotRenderingState
from final_code.states.ToolOptions import ToolOptions
from final_code.pydantic_models.UtGen import UtGeneration


class AgentBuilderState(BaseCopilotRenderingState):
    """
    Represents the state of the main agent building graph.
    Inherits from MessagesState to include a list of messages.
    """
    req_analysis: ReqAnalysis= Field(description="The requirement analysis generated by the model.")
    react_flow_created: bool = Field(default=False, description="Flag to indicate if the ReactFlow graph has been created")
    justification: str = Field(description="Justification for the agent_architecture")
    use_cases: List[UseCaseAnalysis] = Field(default_factory=list,description="List of use cases with their names, descriptions, and dry runs.")
    env_variables: List[str] = Field(description="List if all environment variables required to run the python code")
    tool_set: set = Field(description="The composio tool slugs")
    tool_options: ToolOptions = Field(description="The list of tools provided by the user")
    # eval pipeline
    packages: list[str]
    pytest_results: str = Field(description="The pytest results")
    issue_type: Literal["syntax_error", "runtime_error", "assertion_fail"] = Field(description="identify the type of issue")
    file_that_needs_fixes: Literal["python_code", "mock_tools_code", "pytest_code"] = Field(description="identify the file to fix")
    fix_needed: str = Field(description="detailed explanation of fixes needed, in a diff format")
    attempts: int = Field(default=5, description="Number of attempts made to fix the issue")
    utGeneration: UtGeneration = Field(description="The unit test generation object containing final_response_uts and trajectory_uts")
