from typing import Annotated
from langgraph.graph import MessagesState
from pydantic import Field
from final_code.states.AgentInstructions import AgentInstructions
from final_code.states.ArchEvaluations import ArchEvaluationWithUrl
import operator


class AgentBuilderState(MessagesState):
    """
    Represents the state of the main agent building graph.
    Inherits from MessagesState to include a list of messages.
    """
    agent_instructions: AgentInstructions = Field(description="The requirement analysis generated by the model.")
    json_dict: str = Field(description="The JSON representation of the agent's architecture and nodes")
    reactflow_json: str = Field(description="The JSON representation of the ReactFlow graph for the agent")
    justification: str = Field(description="Justification for the agent_architecture")
    python_code: str = Field(description="The Python code generated for the agent")
    # the below are needed for the old flow
    arch_evaluation_reports: Annotated[list[ArchEvaluationWithUrl], operator.add]
    best_agent_architecture: ArchEvaluationWithUrl = Field(description="the best architecture selected")
    json_code: str = Field(description="Json of the code")
