from typing import Annotated, List
from langgraph.graph import MessagesState
from pydantic import Field
from final_code.states.AgentInstructions import AgentInstructions
from final_code.states.ArchEvaluations import ArchEvaluationWithUrl
from final_code.states.NodesAndEdgesSchemas import JSONSchema
from final_code.states.DryRunState import UseCaseAnalysis
from typing import List
import operator
from copilotkit import CopilotKitState



class AgentBuilderState(CopilotKitState):
    """
    Represents the state of the main agent building graph.
    Inherits from MessagesState to include a list of messages.
    """
    agent_instructions: AgentInstructions = Field(description="The requirement analysis generated by the model.")
    json_schema: JSONSchema = Field(description="The JSON schema of the agent's architecture, including nodes and edges")
    json_dict: str = Field(description="The JSON representation of the agent's architecture and nodes")
    reactflow_json: str = Field(description="The JSON representation of the ReactFlow graph for the agent")
    justification: str = Field(description="Justification for the agent_architecture")
    python_code: str = Field(description="The Python code generated for the agent")
    use_cases: List[UseCaseAnalysis] = Field(default_factory=list,description="List of use cases with their names, descriptions, and dry runs.")
    # the below are needed for the old flow
    arch_evaluation_reports: Annotated[list[ArchEvaluationWithUrl], operator.add]
    best_agent_architecture: ArchEvaluationWithUrl = Field(description="the best architecture selected")
    json_code: str = Field(description="Json of the code")
    env_variables: List[str] = Field(description="List if all environment variables required to run the python code")
